### ISSUE TITLE
Bug for src/util/filterTreeUtil.js

### ISSUE THREAD

**Issue by glennleevx** [MohamadHFallah/react-filter-tree#2]
In the function getIDsExpandFilter (line 86), the existing code only cater for single branch from the root of tree
 ```
 if (children) {
    store.push(children[0].id);
  }
```
In order to cater for entire tree with multiple branches and sub-branches, the following code will do the job
```
if (children) {
    children.map((child) => store.push(child.id));
}
```

**Comment by MohamadHFallah** [comment]
Hi @glennleevx, Thanks for the bug report. it resolved.
